app/roast/forms.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import flash
from flask_wtf import Form
from wtforms import StringField, SelectField, IntegerField, DateTimeField, TextAreaField
from wtforms.validators import DataRequired, Optional


class BeanForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description')


class RoasterForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description')


class RoastForm(Form):
    bean = SelectField('Bean', validators=[DataRequired()])
    roaster = SelectField('Roaster', validators=[DataRequired()])

    start_time = StringField('Start Time', validators=[DataRequired()])
    start_temp = IntegerField('Start Temperature (F)', validators=[Optional()])
    start_weight = IntegerField('Start Weight (g)', validators=[Optional()])

    fc_start_time = StringField('Start Time')
    fc_start_temp = IntegerField('Start Temperature (F)', validators=[Optional()])
    fc_end_time = StringField('End Time')
    fc_end_temp = IntegerField('End Temperature (F)', validators=[Optional()])

    sc_start_time = StringField('Start Time')
    sc_start_temp = IntegerField('Start Temperature (F)', validators=[Optional()])
    sc_end_time = StringField('End Time')
    sc_end_temp = IntegerField('End Temperature (F)', validators=[Optional()])

    end_time = StringField('End Time', validators=[DataRequired()])
    end_temp = IntegerField('End Temperature (F)', validators=[Optional()])
    end_weight = IntegerField('End Weight (g)', validators=[Optional()])

    roast_datetime = StringField('Roast Date', validators=[DataRequired()])
    notes = TextAreaField('Notes')


def flash_form_errors(form, category="warning"):
    for field, errors in form.errors.items():
        for error in errors:
            flash("{0} - {1}".format(getattr(form, field).label.text, error), category)

app/roast/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

roast = Blueprint('roast', __name__, template_folder='templates')

from . import views

app/roast/views.py
from datetime import datetime
from flask import render_template, redirect, url_for, request
from flask.ext.login import login_required, current_user
from app import db
from app.models import Bean, Roaster, Roast
from .forms import BeanForm, RoasterForm, RoastForm, flash_form_errors
from . import roast


@roast.route('/', methods=['GET'])
@login_required
def index():
    roasts = Roast.query.filter_by(user_id=current_user.id).order_by(Roast.roast_datetime.desc()).all()
    beans = Bean.query.filter_by(user_id=current_user.id).all()
    roasters = Roaster.query.filter_by(user_id=current_user.id).all()
    return render_template('roast/index.html', roasts=roasts, beans=beans, roasters=roasters)


@roast.route('/beans', methods=['GET'])
@login_required
def bean_list():
    beans = Bean.query.filter_by(user_id=current_user.id).all()
    return render_template('roast/bean_list.html', beans=beans)


@roast.route('/beans/new', methods=['GET', 'POST'])
@login_required
def bean_new():
    form = BeanForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            bean = Bean(
                name=form.name.data,
                description=form.description.data,
                user_id=current_user.id,
            )
            db.session.add(bean)
            db.session.commit()
            return redirect(url_for('roast.bean_detail', bean_id=bean.id))
        else:
            flash_form_errors(form)
    return render_template('roast/bean_new.html', form=form)


@roast.route('/beans/<int:bean_id>', methods=['GET'])
@login_required
def bean_detail(bean_id):
    bean = Bean.query.get(bean_id)
    return render_template('roast/bean_detail.html', bean=bean)


@roast.route('/beans/edit/<int:bean_id>', methods=['GET', 'POST'])
@login_required
def edit_bean(bean_id):
    if request.method == 'POST':
        form = BeanForm(request.form)
        if form.validate_on_submit():
            bean = Bean.query.get(bean_id)
            bean.name = form.name.data
            bean.description = form.description.data
            db.session.add(bean)
            db.session.commit()
            return redirect(url_for('roast.bean_detail', bean_id=bean.id))
        else:
            flash_form_errors(form)
    bean = Bean.query.get(bean_id)
    form = BeanForm(obj=bean)
    return render_template('roast/bean_edit.html', form=form, bean=bean)


@roast.route('/roasters', methods=['GET'])
@login_required
def roaster_list():
    roasters = Roaster.query.filter_by(user_id=current_user.id).all()
    return render_template('roast/roaster_list.html', roasters=roasters)

@roast.route('/roasters/new', methods=['GET', 'POST'])
@login_required
def roaster_new():
    form = RoasterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            roaster = Roaster(
                name=form.name.data,
                description=form.description.data,
                user_id=current_user.id,
            )
            db.session.add(roaster)
            db.session.commit()
            return redirect(url_for('roast.roaster_detail', roaster_id=roaster.id))
        else:
            flash_form_errors(form)
    return render_template('roast/roaster_new.html', form=form)


@roast.route('/roasters/<int:roaster_id>', methods=['GET'])
@login_required
def roaster_detail(roaster_id):
    roaster = Roaster.query.get(roaster_id)
    return render_template('roast/roaster_detail.html', roaster=roaster)


@roast.route('/roasters/edit/<int:roaster_id>', methods=['GET', 'POST'])
@login_required
def roaster_edit(roaster_id):
    if request.method == 'POST':
        form = RoasterForm(request.form)
        if form.validate_on_submit():
            roaster = Roaster.query.get(roaster_id)
            roaster.name = form.name.data
            roaster.description = form.description.data
            db.session.add(roaster)
            db.session.commit()
            return redirect(url_for('roast.roaster_detail', roaster_id=roaster.id))
        else:
            flash_form_errors(form)
    roaster = Roaster.query.get(roaster_id)
    form = RoasterForm(obj=roaster)
    return render_template('roast/roaster_edit.html', form=form, roaster=roaster)


@roast.route('/roasts', methods=['GET', 'POST'])
@login_required
def roast_list():
    roasts = Roast.query.filter_by(user_id=current_user.id).all()
    return render_template('roast/roast_list.html', roasts=roasts)


@roast.route('/roasts/<int:roast_id>', methods=['GET'])
@login_required
def roast_detail(roast_id):
    roast = Roast.query.get(roast_id)
    return render_template('roast/roast_detail.html', roast=roast)

@roast.route('/roasts/edit/<int:roast_id>', methods=['GET', 'POST'])
@login_required
def roast_edit(roast_id):
    form = RoastForm(request.form)
    beans = Bean.query.filter_by(user_id=current_user.id).all()
    roasters = Roaster.query.filter_by(user_id=current_user.id).all()
    form.bean.choices = [(str(bean.id), bean.name) for bean in beans]
    form.roaster.choices = [(str(roaster.id), roaster.name) for roaster in roasters]

    if request.method == 'POST':
        if form.validate_on_submit():
            roast = Roast.query.get(roast_id)
            roast.bean_id = form.bean.data
            roast.roaster_id = form.roaster.data
            roast.start_time = form.start_time.data
            roast.start_temp = form.start_temp.data
            roast.start_weight = form.start_weight.data
            roast.fc_start_time = form.fc_start_time.data
            roast.fc_start_temp = form.fc_start_temp.data
            roast.fc_end_time = form.fc_end_time.data
            roast.fc_end_temp = form.fc_end_temp.data
            roast.sc_start_time = form.sc_start_time.data
            roast.sc_start_temp = form.sc_start_temp.data
            roast.sc_end_time = form.sc_end_time.data
            roast.sc_end_temp = form.sc_end_temp.data
            roast.end_time = form.end_time.data
            roast.end_temp = form.end_temp.data
            roast.end_weight = form.end_weight.data
            roast.roast_datetime = datetime.strptime(form.roast_datetime.data, "%m/%d/%Y %I:%M:%S %p")
            roast.notes = form.notes.data
            db.session.commit()
            return redirect(url_for('roast.roast_detail', roast_id=roast.id))
        else:
            flash_form_errors(form)
    if request.method == 'GET':
        roast = Roast.query.get(roast_id)
        form = RoastForm(obj=roast)
        form.roast_datetime.data = roast.formatted_datetime
        form.bean.choices = [(str(bean.id), bean.name) for bean in beans]
        form.roaster.choices = [(str(roaster.id), roaster.name) for roaster in roasters]

    return render_template('roast/roast_edit.html', form=form, beans=beans, roasters=roasters, roast=roast)




@roast.route('/roasts/new', methods=['GET', 'POST'])
@login_required
def roast_new():
    form = RoastForm(request.form)
    beans = Bean.query.filter_by(user_id=current_user.id).all()
    roasters = Roaster.query.filter_by(user_id=current_user.id).all()
    form.bean.choices = [(str(bean.id), bean.name) for bean in beans]
    form.roaster.choices = [(str(roaster.id), roaster.name) for roaster in roasters]

    if request.method == 'POST':
        if form.validate_on_submit():
            roast_datetime = datetime.strptime(form.roast_datetime.data, "%m/%d/%Y %I:%M:%S %p")
            roast = Roast(
                user_id=current_user.id,
                bean_id=form.bean.data,
                roaster_id=form.roaster.data,
                start_time=form.start_time.data,
                start_temp=form.start_temp.data,
                start_weight=form.start_weight.data,
                fc_start_time=form.fc_start_time.data,
                fc_start_temp=form.fc_start_temp.data,
                fc_end_time=form.fc_end_time.data,
                fc_end_temp=form.fc_end_temp.data,
                sc_start_time=form.sc_start_time.data,
                sc_start_temp=form.sc_start_temp.data,
                sc_end_time=form.sc_end_time.data,
                sc_end_temp=form.sc_end_temp.data,
                end_time=form.end_time.data,
                end_temp=form.end_temp.data,
                end_weight=form.end_weight.data,
                roast_datetime=roast_datetime,
                notes=form.notes.data,
            )
            db.session.add(roast)
            db.session.commit()
            return redirect(url_for('roast.roast_detail', roast_id=roast.id))
        else:
            flash_form_errors(form)
    return render_template('roast/roast_new.html', form=form, beans=beans, roasters=roasters)

app/roast/templates/roast/bean_detail.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ bean.name }} <span class="pull-right"><a href="{{ url_for('roast.edit_bean', bean_id=bean.id) }}">Edit</a></span></div>
  <div class="panel-body">
    <p>{{ bean.description }}</p>
  </div>
</div>

{% if bean.roasts.all() %}
<h4>Roasts for {{ bean.name }}</h4>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Bean</th>
            <th>Roaster</th>
            <th>Roast Date</th>
        </tr>
    </thead>
    <tbody>
    {% for roast in bean.roasts %}
        <tr>
            <td><a href="{{ url_for('roast.roast_detail', roast_id=roast.id) }}">{{ roast.bean.name }}</a></td>
            <td>{{ roast.roaster.name }}</td>
            <td>{{ roast.formatted_datetime }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}

{% endblock %}

app/roast/templates/roast/bean_edit.html
{% extends "base.html" %}

{% block content %}

<h3>Edit Bean</h3>

<form method="POST" action="{{ url_for('roast.edit_bean', bean_id=bean.id) }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Save" class="btn btn-primary">
  </form>

{% endblock %}

app/roast/templates/roast/bean_list.html
{% extends "base.html" %}

{% block css %}
    {{ super() }}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/nv.d3.min.css') }}" />
{% endblock %}

{% block content %}

<h3>Beans</h3>
{% if beans %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Bean</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    {% for bean in beans %}
        <tr>
            <td><a href="{{ url_for('roast.bean_detail', bean_id=bean.id) }}">{{ bean.name }}</a></td>
            <td>{{ bean.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <p>You currently have no beans. Add some down below.</p>
{% endif %}


<p><a class="btn btn-primary" href="{{ url_for('roast.bean_new') }}">Add Bean</a></p>

<div id="chart">
    <h4>Roasts by Bean</h4>
    <svg></svg>
</div>

<div id="chart2">
    <h4>Roast Weight by Bean</h4>
    <svg></svg>
</div>

{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/d3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/nv.d3.min.js') }}"></script>
    <script type="text/javascript">
        nv.addGraph(function() {
          var chart = nv.models.pieChart()
                          .x(function(d) {return d.label})
                          .y(function(d) {return d.value})
                          .showLabels(true)
          ;

          d3.select('#chart svg')    //Select the <svg> element you want to render the chart in.
              .datum({{ current_user.roasts_by_bean()|safe }})         //Populate the <svg> element with chart data...
              .call(chart);          //Finally, render the chart!

          //Update the chart when window resizes.
          nv.utils.windowResize(function() { chart.update() });
          return chart;
        });

        nv.addGraph(function() {
          var chart = nv.models.pieChart()
                          .x(function(d) {return d.label})
                          .y(function(d) {return d.value})
                          .showLabels(true)
          ;

          d3.select('#chart2 svg')    //Select the <svg> element you want to render the chart in.
              .datum({{ current_user.roast_weight_by_bean()|safe }})         //Populate the <svg> element with chart data...
              .call(chart);          //Finally, render the chart!

          //Update the chart when window resizes.
          nv.utils.windowResize(function() { chart.update() });
          return chart;
        });



    </script>
{% endblock %}

app/roast/templates/roast/bean_new.html
{% extends "base.html" %}

{% block content %}

<h3>Add Bean</h3>
<form method="POST" action="{{ url_for('roast.bean_new') }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Save" class="btn btn-primary">
</form>
{% endblock %}

app/roast/templates/roast/edit_bean.html
{% extends "base.html" %}

{% block content %}

<h3>Edit Bean</h3>

<form method="POST" action="{{ url_for('roast.edit_bean', bean_id=bean.id) }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Submit" class="btn btn-primary btn-block">
  </form>

{% endblock %}

app/roast/templates/roast/edit_roaster.html
{% extends "base.html" %}

{% block content %}

<h3>Edit Roaster</h3>

<form method="POST" action="{{ url_for('roast.edit_roaster', roaster_id=roaster.id) }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Submit" class="btn btn-primary btn-block">
  </form>

{% endblock %}

app/roast/templates/roast/index.html
{% extends "base.html" %}

{% block content %}

{% if beans|length == 0 %}
<p>You have no beans. Add some beans before adding a Roast.</p>
{% endif %}
{% if roasters|length == 0 %}
<p>You have no roasters. Add some roasters before adding a Roast.</p>
{% endif %}

{% if roasts|length > 0 %}
    <h3>Roasts</h3>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Bean</th>
                <th>Roaster</th>
                <th>Roast Date</th>
            </tr>
        </thead>
        <tbody>
        {% for roast in roasts %}
            <tr>
                <td><a href="{{ url_for('roast.roast_detail', roast_id=roast.id) }}">{{ roast.bean.name }}</a></td>
                <td>{{ roast.roaster.name }}</td>
                <td>{{ roast.formatted_datetime }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

<p><a class="btn btn-primary" href="{{ url_for('roast.roast_new') }}">Add New Roast</a></p>

{% endblock %}

app/roast/templates/roast/roast_detail.html
{% extends "base.html" %}

{% block css %}
    {{ super() }}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/nv.d3.min.css') }}" />
{% endblock %}

{% block content %}

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ roast.bean.name }} <span class="pull-right"><a href="{{ url_for('roast.roast_edit', roast_id=roast.id) }}">Edit</a></span></div>
  <div class="panel-body">
    <p>Roasted with {{ roast.roaster.name }} on {{ roast.formatted_datetime }}</p>
    <p>Notes: {{ roast.notes }}</p>
  </div>

  <div class="panel panel-info">
      <div class="panel-heading">Start</div>
      <div class="panel-body">
        <div class="col-xs-3">Time</div>
        <div class="col-xs-9">{{ roast.start_time }}</div>
        <div class="col-xs-3">Temperature</div>
        <div class="col-xs-9">{% if roast.start_temp %}{{ roast.start_temp }}&deg;{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">Weight</div>
        <div class="col-xs-9">{% if roast.start_weight %}{{ roast.start_weight }}g{% else %}&nbsp;{% endif %}</div>
      </div>
  </div>

  <div class="panel panel-info">
      <div class="panel-heading">First Crack</div>
      <div class="panel-body">
        <div class="col-xs-3">Start Time</div>
        <div class="col-xs-9">{% if roast.fc_start_time %}{{ roast.fc_start_time }}{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">End Time</div>
        <div class="col-xs-9">{% if roast.fc_end_time %}{{ roast.fc_end_time }}{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">Start Temperature</div>
        <div class="col-xs-9">{% if roast.fc_start_temp %}{{ roast.fc_start_temp }}&deg;{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">End Temperature</div>
        <div class="col-xs-9">{% if roast.fc_end_temp %}{{ roast.fc_end_temp }}&deg;{% else %}&nbsp;{% endif %}</div>
      </div>
  </div>

  <div class="panel panel-info">
      <div class="panel-heading">Second Crack</div>
      <div class="panel-body">
        <div class="col-xs-3">Start Time</div>
        <div class="col-xs-9">{% if roast.sc_start_time %}{{ roast.sc_start_time }}{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">End Time</div>
        <div class="col-xs-9">{% if roast.sc_end_time %}{{ roast.sc_end_time }}{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">Start Temperature</div>
        <div class="col-xs-9">{% if roast.sc_start_temp %}{{ roast.sc_start_temp }}&deg;{% else %}&nbsp;{% endif %}</div>
        <div class="col-xs-3">End Temperature</div>
        <div class="col-xs-9">{% if roast.sc_end_temp %}{{ roast.sc_end_temp }}&deg;{% else %}&nbsp;{% endif %}</div>
      </div>
  </div>

  <div class="panel panel-info">
      <div class="panel-heading">End</div>
      <div class="panel-body">
        <div class="col-xs-3">Time</div>
        <div class="col-xs-9">{{ roast.end_time }}</div>
        <div class="col-xs-3">Temperature</div>
        <div class="col-xs-9">{% if roast.end_temp %}{{ roast.end_temp }}&deg;{% endif %}</div>
        <div class="col-xs-3">Weight</div>
        <div class="col-xs-9">{% if roast.end_weight %}{{ roast.end_weight }}g{% endif %}</div>
      </div>
  </div>

  <div class="panel panel-info">
      <div class="panel-heading">Other</div>
      <div class="panel-body">
        <div class="col-xs-3">Time Elapsed</div>
        <div class="col-xs-9">{{ roast.time_elapsed }} seconds</div>
        <div class="col-xs-3">Weight Loss</div>
        <div class="col-xs-9">{% if roast.weight_loss %}{{ roast.weight_loss }}g{% endif %}</div>
        <div class="col-xs-3">Percentage Weight Loss</div>
        <div class="col-xs-9">{% if roast.percent_weight_loss %}{{ roast.percent_weight_loss }}%{% endif %}</div>
      </div>
  </div>

</div>
<div id="chart">
    <h4>Roast Temperature Over Time</h4>
    <svg></svg>
</div>

{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/d3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/nv.d3.min.js') }}"></script>
    <script type="text/javascript">
        /*These lines are all chart setup.  Pick and choose which chart features you want to utilize. */
        nv.addGraph(function() {
          var chart = nv.models.lineChart()
                        .margin({left: 100})  //Adjust chart margins to give the x-axis some breathing room.
                        .showLegend(false)
                        .showYAxis(true)        //Show the y-axis
                        .showXAxis(true)        //Show the x-axis
          ;

          chart.xAxis     //Chart x-axis settings
              .axisLabel('Time (s)')
              .tickFormat(d3.format(',r'));

          chart.yAxis     //Chart y-axis settings
              .axisLabel('Temperature (F)')
              .tickFormat(d3.format(',r'));


          chart.tooltips(true);
          chart.tooltipContent(function(key, y, e, graph) {
              return '<p><strong>' + graph.point.label + '</strong><br>' +
                      'Time: ' + graph.point.x + 's<br>Temperature: ' + graph.point.y + '&deg;F</p>'
          });

          /* Done setting the chart up? Time to render it!*/
          var myData = [{
              values: {{ roast.line_chart_data()|safe }}
          }];

          d3.select('#chart svg')    //Select the <svg> element you want to render the chart in.
              .datum(myData)         //Populate the <svg> element with chart data...
              .call(chart);          //Finally, render the chart!

          //Update the chart when window resizes.
          nv.utils.windowResize(function() { chart.update() });
          return chart;
        });



    </script>
{% endblock %}

app/roast/templates/roast/roaster_detail.html
{% extends "base.html" %}

{% block content %}

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ roaster.name }} <span class="pull-right"><a href="{{ url_for('roast.roaster_edit', roaster_id=roaster.id) }}">Edit</a></span></div>
  <div class="panel-body">
    <p>{{ roaster.description }}</p>
  </div>
</div>

{% if roaster.roasts.all() %}
<h4>Roasts for {{ roaster.name }}</h4>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Bean</th>
            <th>Roaster</th>
            <th>Roast Date</th>
        </tr>
    </thead>
    <tbody>
    {% for roast in roaster.roasts %}
        <tr>
            <td><a href="{{ url_for('roast.roast_detail', roast_id=roast.id) }}">{{ roast.bean.name }}</a></td>
            <td>{{ roast.roaster.name }}</td>
            <td>{{ roast.formatted_datetime }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}

{% endblock %}

app/roast/templates/roast/roaster_edit.html
{% extends "base.html" %}

{% block content %}

<h3>Edit Roaster</h3>

<form method="POST" action="{{ url_for('roast.roaster_edit', roaster_id=roaster.id) }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Save" class="btn btn-primary">
  </form>

{% endblock %}

app/roast/templates/roast/roaster_list.html
{% extends "base.html" %}

{% block css %}
    {{ super() }}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/nv.d3.min.css') }}" />
{% endblock %}

{% block content %}

<h3>Roasters</h3>
{% if roasters %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Roaster</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    {% for roaster in roasters %}
        <tr>
            <td><a href="{{ url_for('roast.roaster_detail', roaster_id=roaster.id) }}">{{ roaster.name }}</a></td>
            <td>{{ roaster.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <p>You currently have no Roasters. Add some down below.</p>
{% endif %}


<p><a class="btn btn-primary" href="{{ url_for('roast.roaster_new') }}">Add Roaster</a></p>


<div id="chart">
    <h4>Roasts by Roaster</h4>
    <svg></svg>
</div>

<div id="chart2">
    <h4>Roast Weight by Roaster</h4>
    <svg></svg>
</div>

{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/d3.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/nv.d3.min.js') }}"></script>
    <script type="text/javascript">
        nv.addGraph(function() {
          var chart = nv.models.pieChart()
                          .x(function(d) {return d.label})
                          .y(function(d) {return d.value})
                          .showLabels(true)
          ;

          d3.select('#chart svg')    //Select the <svg> element you want to render the chart in.
              .datum({{ current_user.roasts_by_roaster()|safe }})         //Populate the <svg> element with chart data...
              .call(chart);          //Finally, render the chart!

          //Update the chart when window resizes.
          nv.utils.windowResize(function() { chart.update() });
          return chart;
        });

        nv.addGraph(function() {
          var chart = nv.models.pieChart()
                          .x(function(d) {return d.label})
                          .y(function(d) {return d.value})
                          .showLabels(true)
          ;

          d3.select('#chart2 svg')    //Select the <svg> element you want to render the chart in.
              .datum({{ current_user.roast_weight_by_roaster()|safe }})         //Populate the <svg> element with chart data...
              .call(chart);          //Finally, render the chart!

          //Update the chart when window resizes.
          nv.utils.windowResize(function() { chart.update() });
          return chart;
        });



    </script>
{% endblock %}

app/roast/templates/roast/roaster_new.html
{% extends "base.html" %}

{% block content %}

<h3>Add Roaster</h3>
<form method="POST" action="{{ url_for('roast.roaster_new') }}">
    {{ form.csrf_token }}
    {{ form.name(placeholder="Name", class_="form-control") }}<br/>
    {{ form.description(placeholder="Description", class_="form-control") }}<br/>
    <input type="submit" value="Save" class="btn btn-primary">
</form>
{% endblock %}